In [30]:
import pandas as pd

In [31]:
mydataset = {
  'cars': ["BMW", "Volvo", "Ford", "Tesla", "Ferrari", "ford", "BMW"],
  'counts': [3, 7, 2, 5, 6, 4, 8]
}

df = pd.DataFrame(mydataset)

print(df)

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       5
4  Ferrari       6
5     ford       4
6      BMW       8

In [32]:
df.head() # default 5 rows

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       5
4  Ferrari       6

In [33]:
df.tail(-1) # deafault 5 rows

      cars  counts
1    Volvo       7
2     Ford       2
3    Tesla       5
4  Ferrari       6
5     ford       4
6      BMW       8

In [34]:
df.shape

(7, 2)

In [35]:
df.columns

Index(['cars', 'counts'], dtype='object')

In [36]:
df.dtypes

cars      object
counts     int64
dtype: object

In [37]:
print(df)

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       5
4  Ferrari       6
5     ford       4
6      BMW       8

In [38]:
df.describe() #numerical columns only

         counts
count  7.000000
mean   5.000000
std    2.160247
min    2.000000
25%    3.500000
50%    5.000000
75%    6.500000
max    8.000000

In [39]:
df.iloc[2:]

      cars  counts
2     Ford       2
3    Tesla       5
4  Ferrari       6
5     ford       4
6      BMW       8

In [40]:
df.loc[3, "cars"]

'Tesla'

In [41]:
print(df)

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       5
4  Ferrari       6
5     ford       4
6      BMW       8

In [42]:
df[df["cars"] == "BMW"]

  cars  counts
0  BMW       3
6  BMW       8

In [43]:
# df.mean(numric_only=True)
df["counts"].mean()

np.float64(5.0)

In [44]:
df.sum()

cars      BMWVolvoFordTeslaFerrarifordBMW
counts                                 35
dtype: object

In [45]:
df.min()

cars      BMW
counts      2
dtype: object

In [46]:
df.max()

cars      ford
counts       8
dtype: object

In [47]:
df.median(numeric_only=True)

counts    5.0
dtype: float64

In [48]:
df.count()

cars      7
counts    7
dtype: int64

In [49]:
data_with_missing = {
  'cars': ["BMW", "Volvo", None, "Ford", "Tesla", "Ferrari", None, "BMW"],
  'counts': [3, None, 1, 9, 5, 6, 4, None]
}
df_missing = pd.DataFrame(data_with_missing)

print(df_missing)

      cars  counts
0      BMW     3.0
1    Volvo     NaN
2     None     1.0
3     Ford     9.0
4    Tesla     5.0
5  Ferrari     6.0
6     None     4.0
7      BMW     NaN

In [50]:
df_missing.isnull().sum()

cars      2
counts    2
dtype: int64

In [51]:
df_missing.dropna(subset=["cars"])

      cars  counts
0      BMW     3.0
1    Volvo     NaN
3     Ford     9.0
4    Tesla     5.0
5  Ferrari     6.0
7      BMW     NaN

In [52]:
df_missing.fillna({"cars": "unknown", "counts": 0})

      cars  counts
0      BMW     3.0
1    Volvo     0.0
2  unknown     1.0
3     Ford     9.0
4    Tesla     5.0
5  Ferrari     6.0
6  unknown     4.0
7      BMW     0.0

In [53]:
# df = pd.read_csv("Titanic-Dataset.csv")

df.to_excel("test.xlsx")
df.tail()


# df = pd.read_json("Titanic-Dataset.json")

      cars  counts
2     Ford       2
3    Tesla       5
4  Ferrari       6
5     ford       4
6      BMW       8

In [54]:
df.to_excel("test.xlsx")

In [55]:
# Series => 1d
cars = pd.Series(["BMW", "Tesla", "Ferrari"])
print(cars)

0        BMW
1      Tesla
2    Ferrari
dtype: object

In [56]:
cars_series = data_with_missing['cars']
print(cars_series)

['BMW', 'Volvo', None, 'Ford', 'Tesla', 'Ferrari', None, 'BMW']